# Generated by Django 5.0.6 on 2024-06-27 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('katakunci', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HasilLDA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_topics', models.IntegerField()),
                ('coherence_score', models.IntegerField()),
                ('hasil', models.TextField()),
                ('analisis', models.TextField()),
                ('id_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.history')),
            ],
        ),
        migrations.CreateModel(
            name='DataBerita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.history')),
            ],
        ),
    ]
