# Generated by Django 5.0.6 on 2024-07-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_role_databerita_judul_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='history',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
    ]
