# Generated by Django 5.0.6 on 2024-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_role_databerita_judul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasillda',
            name='coherence_score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
