# Generated by Django 5.0.6 on 2024-07-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_history_user_id_history_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasillda',
            name='coherence_score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
