# Generated by Django 5.0.6 on 2024-07-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_hasillda_coherence_score'),
        ('mysite', '0004_alter_hasillda_coherence_score'),
    ]

    operations = [
    ]
