# Generated by Django 5.0.6 on 2024-07-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_merge_20240726_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasillda',
            name='perplexity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hasillda',
            name='coherence_score',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
